version: "3"

services:
    jenkins:
        ports:
            - 8080:8080
        volumes:
            - ./my_marvin.yml:/var/jenkins_conf
            - jenkins_home:/var/jenkins_home
        environment:
            - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
            - USER_NASSO_PASSWORD=root
            - USER_I_DONT_KNOW_PASSWORD=root
            - USER_VAUGIE_G_PASSWORD=root
            - USER_CHOCOLATEEN_PASSWORD=admin
            - CASC_JENKINS_CONFIG=/var/jenkins_conf/
        build:
            context: "."

volumes:
    jenkins_home: