jenkins:
  systemMessage:  "Welcome to the Whanos Jenkins Instance."
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${USER_ADMIN_PASSWORD}
          name: "admin"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"

jobs:
  - file: /usr/share/jenkins/ref/init.groovy.d/job_dsl.groovy